# Language and env

language: node_js
node_js: v12
cache: npm

# Travis Lifecycle
before_script: npm run build

# Ajoute les artéfacts au déploiement
before_deploy:
- mkdir ./dist
- cp *.html ./dist
- cp robots.txt ./dist
- cp -rf build ./dist && rm ./dist/build/.gitignore
- cp -rf data ./dist
- cp -rf public ./dist
- cp -rf images ./dist

deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: master

# Other configs

git:
  depth: 10
